package com.pratian.many_to_one_uni;

import java.sql.Date;

import org.hibernate.Session;
import org.hibernate.SessionFactory;

public class TestMain1 {

	public static void main(String[] args) {
		// Get Session factory and session
		SessionFactory sf = HibernateUtil.getSessionFactory();
		Session session = sf.openSession();

		// Begin transaction
		session.beginTransaction();

		// Create Customer and save it to DB
		Date date = Date.valueOf("1995-03-24");
		Customer_M_1_Uni customer1= new Customer_M_1_Uni("Chandra",date,"1234567890","chandra@gmaill.com"); 
		session.save(customer1);
		System.out.println(customer1.getCustomerId());
		// Since, customer1 is participating in persistence. 
		// When session.save() is performed customer1 will be in Persistent state.
		// The customer_id generated by DB is also added and make available to 
		// customer1
				 
		// Create Reservation and save it to DB
		Reservation_M_1_Uni reservation1= new Reservation_M_1_Uni( "Confirmed", "Email"); 
		reservation1.setCustomer(customer1);
		session.save(reservation1);
				 
		// Create Reservation and save it to DB
		Reservation_M_1_Uni reservation2= new Reservation_M_1_Uni( "Pending", "Person"); 
		reservation2.setCustomer(customer1); 
		session.save(reservation2);
				 
		// Create Reservation and save it to DB
		Reservation_M_1_Uni reservation3= new Reservation_M_1_Uni( "Cancelled", "Email"); 
		reservation3.setCustomer(customer1); 
		session.save(reservation3);

		// Commit
		session.getTransaction().commit();
		
		// Close the session
		session.close();
	}

}
